server:
  port: 8083
  servlet:
    context-path: /api
spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/bookinghealth"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  application:
    name: "booking-health"

#Config cloudinary
cloudinary:
  cloud-name: "dujh6cwsj"
  api-key: "863423677598261"
  api-secret: "TpCqRyHXlJ-xFzVj_KAJb9VDMO4"
  folder-name: "booking-health"

jwt:
  signerKey: "527bda0702998f7cf3d981f40d37bfe17aee1d39e4b1e14e1faf419d404a103e"
  valid-duration: 3600

#Config LocationIQ Geocoding
locationiq:
  api:
    key: "pk.96e9f8e6ed76e5de53ce881168c84905"